### ISSUE TITLE
Exporting model to onnx format 

### ISSUE THREAD

**Issue by anilsathyan7** [ZHKKKe/MODNet#10]
How to export model to onnx format?
I tried the following with colab demo code , but it showed an error:
 **TypeError: forward() missing 1 required positional argument: 'inference'**

```
from torch.autograd import Variable

model = MODNet(backbone_pretrained=False)
model = nn.DataParallel(model).cuda()

state_dict = torch.load(pretrained_ckpt)
model.load_state_dict(state_dict)
model.eval()
dummy_input = Variable(torch.randn(1, 3, 512, 512))
torch.onnx.export(model.module, dummy_input, '/content/MODNet/modnet.onnx', export_params = True)
```

BTW the test results looks amazing !!!

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention!


Please refer to the forward function of  MODNet defined in the file `MODNet/src/models/modnet.py`. This function takes an argument `inference` as the input. Set `inference = True` will disable the outputs of LRBranch and HRBranch, *i.e.*, s_p and d_p in the paper, to save the inference time.

I am not familiar with onnx, but it seems that onnx does not support conditional statements in the forward function. A possible solution may be to rewrite the forward function by deleting the code related to the argument `inference`.

**Comment by anilsathyan7** [comment]
Thanks, it worked !!!

**Comment by manthanTECHNOZER** [comment]
I got the error like this:
`RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type NoneType
`
I don't know, what going wrong!

**Comment by Tomas1337** [comment]
Hi, would you mind sharing your work on the onnx model? I'm trying to do the same but to export it to an OpenVino model after.

I'm pretty new to this so i'm finding my way through. It looks like you exported the entire MODnet to onnx. Wouldnt you have to export each of the three models to ONNX? (LR, HR, FR?)

**Comment by Tomas1337** [comment]
Also, "Set inference = True will disable the outputs of LRBranch and HRBranch"

Do you not need the LR and HR branch when doing inference?

**Comment by manthan3C273** [comment]
@ZHKKKe First of all, Thank you for such an amazing work. I really appreciate it. 

As you suggested above, I was able to generate .onnx file by modifying your code but got this warning. 

`/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_helper.py:267: UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 9. This operator might cause results to not match the expected results by PyTorch.
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
We recommend using opset 11 and above for models using this operator. 
  "" + str(_export_onnx_opset_version) + ". "`

I also tried to inference with this model by using this [tutorial](https://thenewstack.io/tutorial-using-a-pre-trained-onnx-model-for-inferencing/). 

But I couldn't start InferenceSession. It gives an error as below:

`RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/upsample.h:277 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale >= 1 was false. Scale value should be greater than or equal to 1.`

 I couldn't figure out. Can you help me or suggest anything so that I can do with it. 

Following work is mention below in Colab notebook. 
[Colab](https://colab.research.google.com/drive/1DxoXenxPLcnVYMCN6STDgmVCOXg6E7M1?usp=sharing)
[Here ](https://drive.google.com/file/d/1tvt07XBiyeqQnwNziaHlSU5jj2Uk5OX9/view?usp=sharing) is the link of onnx model.

**Comment by Tomas1337** [comment]
I've gotten it to work on onnx.
Have you tried passing on the opset parameter to be 11? Worked for me

**Comment by manthan3C273** [comment]
Okay, Thank you for help. I completely misunderstood the error. It also worked for me. I updated the onnx file [here](https://drive.google.com/file/d/1jdObmfZRBZnMnGW2FF_TS2vylfOEEOEM/view?usp=sharing).

**Comment by ZHKKKe** [comment]
@manthan3C273 Hey, could I share the converted onnx model with the community by adding it to this Repo and README?

**Comment by ZHKKKe** [comment]
@anilsathyan7 @manthanTECHNOZER @Tomas1337 @manthan3C273 
Hey, all, sorry for late response (due to my vacation). Would you like to share the converted onnx model and the inference code of the onnx model with the community? 
If so, you can share the model and the code with me (I will add them into this Repo), or you canb open a pull request (please let me know first under this question).
Thanks in advance.

**Comment by manthan3C273** [comment]
Okay sure. I'll share it with you soon.

**Comment by manthan3C273** [comment]
Okay, sure. I'll do it. But I'm getting dependencies of torch for **F. interpolate**. Because I got to know that your processed image of inference is looking like this. 

`import matplotlib.pyplot as plt

im = F.interpolate(im, size=(im_rh, im_rw), mode='area')
im_np = np.asarray(im)
im_np = im_np.reshape((im_rh, im_rw, 3))

plt.imshow(im_np)
`
[Output image](https://drive.google.com/file/d/1mTF4OyZr7Y0jw7Lz2Bqtl9I_bmOfg8sT/view?usp=sharing)

Can you help that how can I pre-process input image without F.interpolate. I think, It may be any option in opencv.  But I didn't know that much about opencv.

**Comment by manthan3C273** [comment]
I just found the solution. I did it in wrong way. Soon I'll share the model and code.
