### ISSUE TITLE
d_size and e_size of trimap 

### ISSUE THREAD

**Issue by andy910389** [ZHKKKe/MODNet#110]
I just used the trimap generation code you provided,
____
from scipy.ndimage import grey_dilation, grey_erosion
self.im_size=512 
trimap = (matte >= 0.9).astype('float32')
not_bg = (matte > 0).astype('float32')
d_size = self.im_size // 256 * random.randint(10, 20)
e_size = self.im_size // 256 * random.randint(10, 20)
trimap[np.where((grey_dilation(not_bg, size=(d_size, d_size))
    - grey_erosion(trimap, size=(e_size, e_size))) != 0)] = 0.5

____

But I found the dilation of trimap image is over.
Like this:
[https://imgur.com/a/RJaG2D0](url)
I think the problem is that the person ration is small.
I directly set d_size and e_size is 2, and then the image is OK.
[https://imgur.com/a/UumOsFW](url)  

My question is,  
1. How can I set the hyper parameter d_size / e_size ? The fixed value is a bad method, because person pixel ratio in my dataset is large or small.
2. For the trimap of [https://imgur.com/a/UumOsFW](url)  
I found that the floor under my feet is a bit gray, does it effect the model training?

**Comment by ZHKKKe** [comment]
Hi, for your questions:


**Q1:How can I set the hyper parameter d_size / e_size ? The fixed value is a bad method, because person pixel ratio in my dataset is large or small.**

You may can try to set `d_size' and `e_size' based on the bounding box of the alpha matte, as:
```
d_size = bbox_size // 256 * random.randint(10, 20)
```
where `bbox_size' can be calculated by OpenCV.

Since the trimap is only used to calculate the loss of detail, the huge trimap will not have much impact on the training process.
In my case, I use the provided code, even though our dataset contains small or large persons.

**Q2: I found that the floor under my feet is a bit gray, does it effect the model training?**
I think it will not effect the training process.

**Comment by andy910389** [comment]
> Hi, for your questions:
> 
> **Q1:How can I set the hyper parameter d_size / e_size ? The fixed value is a bad method, because person pixel ratio in my dataset is large or small.**
> 
> You may can try to set `d_size' and `e_size' based on the bounding box of the alpha matte, as:
> 
> ```
> d_size = bbox_size // 256 * random.randint(10, 20)
> ```
> 
> where `bbox_size' can be calculated by OpenCV.
> 
> Since the trimap is only used to calculate the loss of detail, the huge trimap will not have much impact on the training process.
> In my case, I use the provided code, even though our dataset contains small or large persons.
> 
> **Q2: I found that the floor under my feet is a bit gray, does it effect the model training?**
> I think it will not effect the training process.

Thanks for reply. The person bounding box have width and height, so what value did you use for  the bbox_size?
And I want to know what is the 256 mean?

In my code, I randomly resize the height of person bounding box with original ratio from 256 to 768, and then overlay it to background with 512*512.
So maybe I can not use "256", What value  do you suggest in my case? Many thanks!

**Comment by ZHKKKe** [comment]
You may can try to use the short size of the person bounding box (or the mean of bbox width and height) to calculate  `d_size' and `e_size'.
Please use `bbox_size / 256' instead of `bbox_size // 256'. This step calculate a normalization scale for each person bbox. Then you can set a constant `d_constant' (You have to adjust this constant based on your dataset). Finally, you have an adaptive `d_size', as:
```
d_size = (bbox_size / 256) * d_constant
```
In this way, `d_size' can be adapted to diverse person scale.
