### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by andriyrizhiy** [ZHKKKe/MODNet#2]
Can you release your training code?

**Comment by ZHKKKe** [comment]
Hi! Thanks for your attention!

We are doing some necessary preparations for the release. I am sorry that it will take some time (it may be several weeks) since this project is now developing by me alone. We plan to provide an online image/video matting demo (including pre-trained models) for easy usage first. We then will publish the training code, and finally, the validation benchmark.

Looking forward to your continued attention. :)

**Comment by jacksongoode** [comment]
Glad to see it! How are you planning to release the demo (on what platform)?

**Comment by ZHKKKe** [comment]
@jacksongoode 

We plan to release (1) a Google Colab for image matting demo and (2) a video matting demo that supports WebCam under Ubuntu (We will attempt to build executable versions for Windows and Mac, but now I cannot guarantee that they will be supported).

\* Our code is based on Python 3 and PyTorch >= 1.0.

If you have any good suggestions, please let us know :)

**Comment by ak9250** [comment]
@ZHKKKe colab will probably be the easiest way and it will avoid bugs in the future that are related to environment differences

**Comment by ZHKKKe** [comment]
@ak9250 
Yes. Thanks for your suggestion. I just found that colab has already supported WebCam. 
I will try to develop the video demo based on it. 
However, it seems not easy to provide real-time ablation comparisons (for SOC and OFD in the paper) through colab.
