### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by 99991** [ZHKKKe/MODNet#25]
The README file says that this project is released under the CC-BY-NC-SA 4.0 license.

Does this affect the images produced with the network? Usually, the license of a tool does not affect the license of the output of the tool, except if specified in the license. For example, the license for Adobe's Deep Image Matting dataset explicitly states that models trained on their images can only be used for non-commercial purposes, so I just wanted to ask to make sure this is not the case here.

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

This project includes our code, pre-trained models, demos, etc. It means that you cannot use our code, pre-trained models, and demos for commercial purposes. For example, you cannot integrate our pre-trained models into a commercial applications. 
In the other word, everything in this repo provided by us only be used for non-commercial purposes under the CC-BY-NC-SA 4.0 license.

Since you can use our pre-trained models or demos for research  or personal purposes, we do not have any restrictions on using the output images obtained by using our pre-trained models or demos. You need to follow the original license of the input images to use it. 

I hope the above expression is clear.

**Comment by 99991** [comment]
Great to hear, thanks!
