### ISSUE TITLE
Demo result is far from good

### ISSUE THREAD

**Issue by QuantumLiu** [ZHKKKe/MODNet#33]
Thank you for this excellent work.
However,there is a big gap between test results and description. There is obvious jitter at the edge and wrong classifications.
Do you have any plan to improve ?
![image](https://user-images.githubusercontent.com/21980268/102902337-d34af980-44a9-11eb-9856-910ee2f4493c.png)

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention!

Our demo is possible to be wrong in your case because our semantic estimation is not accurate enough (due to our insufficient labeled data). You can try to remove cloths from the background or in a brighter light condition for better results. We are currently trying to improve performance.

**Comment by juzuo** [comment]
Looking forward to see a better modnet. 👍

**Comment by ZHKKKe** [comment]
@juzuo Thanks. We are trying to solve the remain problems. 
I hope we can see the version 2 of MODNet in the future.

**Comment by LianShuaiLong** [comment]
> @juzuo Thanks. We are trying to solve the remain problems.
> I hope we can see the version 2 of MODNet in the future.

Looking forward to MODNetv2
