### ISSUE TITLE
Shouldn't images be normalized using ImageNet stats?

### ISSUE THREAD

**Issue by FraPochetti** [ZHKKKe/MODNet#79]
Hi,
I noticed [here](https://github.com/ZHKKKe/MODNet/blob/fe1e82c65d6a5009f3c4f7ee82191f427e871b10/demo/image_matting/colab/inference.py#L41) that you normalize images using the following stats `(0.5, 0.5, 0.5), (0.5, 0.5, 0.5)`, instead of the ImageNet ones.
I know this is the inference code, but I assume the same happens at training.
Is there any reason behind that?
Given you are using a pre-trained MobileNetV2 architecture, I would have guessed ImageNet normalization to be a must.
Thanks!

**Comment by ZHKKKe** [comment]
The ImageNet normalization is calculated among all images on ImageNet. 
However, if you calculate the mean and variance among infinite images, the mean and variance should be `(0.5, 0.5, 0.5), (0.5, 0.5, 0.5)`. Since we want to adapt the model to any images, we use `(0.5, 0.5, 0.5), (0.5, 0.5, 0.5)`.

(I think the mean and variance of ImageNet is used to obtain best classification results.)

**Comment by FraPochetti** [comment]
Got it, thanks.
