### ISSUE TITLE
training code not complete?

### ISSUE THREAD

**Issue by txytju** [ZHKKKe/MODNet#82]
Thanks for sharing your great work!
I'm trying to train modnet on my own datast but I found that the training code seems to be uncomplete, so can you share all of your training code? Thanks!

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

I am sorry that the whole training code will not be published until this work is accepted by a conference or a journal.

**Comment by enclarify** [comment]
I was about to attempt training myself because I am not getting great results with the pre-trained models. What is missing from the training code?

**Comment by ZHKKKe** [comment]
@enclarify 
Hi, you need to implement a data loader to load your own data.

**Comment by enclarify** [comment]
@ZHKKKe 

That makes sense. I was already planning on doing that and implement the OFD. Thanks!

**Comment by Fight-hawk** [comment]
@enclarify 我实现了完整的训练代码 训练了几个模型 难以打到开源模型的效果 欢迎一起探讨一下

**Comment by enclarify** [comment]
@Fight-hawk I would love to collaborate. 

What was your training set? Did you build the training set yourself? I have implemented some high quality deep learning matting approaches and am building a custom training set with a depth camera to build the trimaps. I haven't gotten to the point of building new models yet because I am focused on some other features of the application I am building but will get back to it soon.
